### PR TITLE
Add SPI_CLOCK_30MHz for F_BUS == 60000000

### PR DESCRIPTION
**Pull request by FrankBoesing**

### CODE REVIEW

**Comment by xseignard** [comment]
Hello,
Any idea why this hasn't been merged? It is a must have when working with the artnet protocol with the Wiz820io/Wiz850io ethernet module (and in many other cases I guess).

Best regards

**Comment by PaulStoffregen** [comment]
SPI.beginTransaction() should be used to set the SPI clock speed, even if using SPIFIFO.  See the Ethernet library for an example.

**Comment by xseignard** [comment]
Hello, thanks for the answer.

I see in the w5500 datasheet that it can run SPI to 80MHz, is this achievable with a teensy?

Regards

**Comment by PaulStoffregen** [comment]
Let's discuss how to do stuff on the forum, not github issues (especially not closed ones).

**Pull request closed without merging**
