### PR TITLE
Add recommended 24MHz crystal setting

### PR DESCRIPTION
**Pull request by FrankBoesing**
Later, we should check if we can reduce the bias, also (For me, it works with minimal bias -but I think should should keep it for now, as it is).

### CODE REVIEW

**Comment by FrankBoesing** [comment]
Page 1175

**Comment by PaulStoffregen** [comment]
Maybe this should be |= ?  Otherwise it will write zeros to all 31 other bits.  Bits 28-26 are described as "This is not a field that the user would normally need to modify".

**Comment by FrankBoesing** [comment]
This sets bits only:
```
#define PMU_MISC0			(IMXRT_PMU.offset150)
**#define PMU_MISC0_SET			(IMXRT_PMU.offset154)**
#define PMU_MISC0_CLR			(IMXRT_PMU.offset158)
```

**Comment by PaulStoffregen** [comment]
Oh, missed the _SET part.

**Pull request merged**
