### PR TITLE
RX with 4 transfers using similar code to seremu

### PR DESCRIPTION
**Pull request by KurtE**
Testing against issues of hang from thread:
https://forum.pjrc.com/threads/59881-RawHID-recv()-hangs-after-updating-to-Teensyduino-1-4-9-or-higher-for-Teensy-4-0

@PaulStoffregen - The RX now has 4 transfers and more or less same RX code as SEREMU except not worrying about partial frames and the other SEREMU Stuff.  

Like Seremu I did put the RX buffer into DMAMEM, but have not touched the TX Buffer yet which is still in main memory. 

Currently running on two T4.x boards talking to each other. 

Here is a modified one that would have hung but modified to check a 4 byte sequence number instead of a fixed number:
```
#include <Arduino.h>

extern "C" {
  extern char * _sbrk(int incr);
}
void blink(int num);
void setup()
{
  while (!Serial && millis() < 3000) ;
  Serial.begin(115200);
  delay(500); // Simulate initialization
  pinMode(13, OUTPUT);
  pinMode(0, OUTPUT);
  pinMode(1, OUTPUT);
  pinMode(2, OUTPUT);
  pinMode(3, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
  blink(1);
}

char rx_buffer[64];

elapsedMicros time;
uint32_t loop_count = 0;
uint32_t receive_count = 0;
uint32_t valid_count = 0;
uint32_t last_seq_num = (uint32_t) - 1;

void loop()
{
  uint32_t seq_num;
  if (time < 100)
  {
    return;
  }
  loop_count++;
  int n = RawHID.recv(rx_buffer, 1);
  if (n > 0)
  {
    receive_count++;
    seq_num = rx_buffer[0] + (uint32_t)(rx_buffer[1] << 8)
              + (uint32_t)(rx_buffer[2] << 16) + (uint32_t)(rx_buffer[3] << 24);
    if (seq_num != (last_seq_num + 1)) Serial.printf("Seq number change %d %d\n",
          last_seq_num, seq_num);
    last_seq_num = seq_num;
    blink(2);
  }
  time = 0;
  if ((loop_count & 0x7f) == 0) Serial.printf("L:%u R:%u: Seq:%d  Heap: %x\n", loop_count, receive_count,
        last_seq_num, (uint32_t)_sbrk(0));
}

void blink(int num)
{
  for (int i = 0; i < num; i++)
  {
    digitalWrite(13, HIGH);
    delay(10);
    digitalWrite(13, LOW);
    delay(10);
  }
}
```

And the one I ran on the other side to drive it.  Note it could be simplified... 
```
// Simple test of USB Host Mouse/Keyboard
//
// This example is in the public domain

#include "USBHost_t36.h"

USBHost myusb;
USBHub hub1(myusb);
USBHIDParser hid1(myusb);
USBHIDParser hid2(myusb);
USBHIDParser hid3(myusb);
RawHIDController rawhid1(myusb);
RawHIDController rawhid2(myusb, 0xffc90004);
uint8_t serial1buffer[256];


USBDriver *drivers[] = {&hub1, &hid1, &hid2, &hid3};
#define CNT_DEVICES (sizeof(drivers)/sizeof(drivers[0]))
const char * driver_names[CNT_DEVICES] = {"Hub1", "HID1" , "HID2", "HID3"};
bool driver_active[CNT_DEVICES] = {false, false, false, false};

// Lets also look at HID Input devices
USBHIDInput *hiddrivers[] = {&rawhid1, &rawhid2};
#define CNT_HIDDEVICES (sizeof(hiddrivers)/sizeof(hiddrivers[0]))
const char * hid_driver_names[CNT_DEVICES] = {"RawHid1", "RawHid2"};
bool hid_driver_active[CNT_DEVICES] = {false, false};
bool show_changed_only = false;


void setup()
{
  while (!Serial) ; // wait for Arduino Serial Monitor
  Serial4.begin(115200);  // leave default speed for now.
  Serial.println("\n\nUSB Host Testing");
  Serial.println(sizeof(USBHub), DEC);
  myusb.begin();
  rawhid1.attachReceive(OnReceiveHidData);
  rawhid2.attachReceive(OnReceiveHidData);
  pinMode(13, OUTPUT);
  Serial1.begin(115200);  // Debug output...
}

uint32_t loop_count = 0;
void loop()
{
  myusb.Task();

  if (Serial.available()) {
    int ch = Serial.read(); // get the first char.
    while (Serial.read() != -1) ;
    if (show_changed_only) {
      show_changed_only = false;
      Serial.println("\n*** Show All fields mode ***");
    } else {
      show_changed_only = true;
      Serial.println("\n*** Show only changed fields mode ***");
    }
  }
  int cbSerial1;
  if ((cbSerial1 = min(Serial1.available(), sizeof(serial1buffer)))) {
    int cba = Serial.availableForWrite();
    if (cba < cbSerial1) cbSerial1 = cba;
    Serial1.readBytes(serial1buffer, cbSerial1);
    Serial.write(serial1buffer, cbSerial1);
  }

  for (uint8_t i = 0; i < CNT_DEVICES; i++) {
    if (*drivers[i] != driver_active[i]) {
      if (driver_active[i]) {
        Serial.printf("*** Device %s - disconnected ***\n", driver_names[i]);
        driver_active[i] = false;
      } else {
        Serial.printf("*** Device %s %x:%x - connected ***\n", driver_names[i], drivers[i]->idVendor(), drivers[i]->idProduct());
        driver_active[i] = true;

        const uint8_t *psz = drivers[i]->manufacturer();
        if (psz && *psz) Serial.printf("  manufacturer: %s\n", psz);
        psz = drivers[i]->product();
        if (psz && *psz) Serial.printf("  product: %s\n", psz);
        psz = drivers[i]->serialNumber();
        if (psz && *psz) Serial.printf("  Serial: %s\n", psz);
      }
    }
  }

  for (uint8_t i = 0; i < CNT_HIDDEVICES; i++) {
    if (*hiddrivers[i] != hid_driver_active[i]) {
      if (hid_driver_active[i]) {
        Serial.printf("*** HID Device %s - disconnected ***\n", hid_driver_names[i]);
        hid_driver_active[i] = false;
      } else {
        Serial.printf("*** HID Device %s %x:%x - connected ***\n", hid_driver_names[i], hiddrivers[i]->idVendor(), hiddrivers[i]->idProduct());
        hid_driver_active[i] = true;

        const uint8_t *psz = hiddrivers[i]->manufacturer();
        if (psz && *psz) Serial.printf("  manufacturer: %s\n", psz);
        psz = hiddrivers[i]->product();
        if (psz && *psz) Serial.printf("  product: %s\n", psz);
        psz = hiddrivers[i]->serialNumber();
        if (psz && *psz) Serial.printf("  Serial: %s\n", psz);
      }
    }
  }
  // See if we have some RAW data
  if (rawhid1) {
    uint8_t buffer[64];
    digitalWriteFast(13, !digitalReadFast(13));
    memset(buffer, 0, sizeof(buffer));
    loop_count++;
    buffer[0] = (loop_count & 0xff);
    buffer[1] = (loop_count >> 8) & 0xff;
    buffer[2] = (loop_count >> 16) & 0xff;
    buffer[3] = (loop_count >> 24) & 0xff;
    rawhid1.sendPacket(buffer);
    delay(100);
  }

}
bool OnReceiveHidData(uint32_t usage, const uint8_t *data, uint32_t len) {
  // Called for maybe both HIDS for rawhid basic test.  One is for the Teensy
  // to output to Serial. while still having Raw Hid...
  if (usage == 0xffc90004) {
    // Lets trim off trailing null characters.
    while ((len > 0) && (data[len - 1] == 0)) {
      len--;
    }
    if (len) {
      Serial.print("RawHid Serial: ");
      Serial.write(data, len);
    }
  } else {
    Serial.print("RawHID data: ");
    Serial.println(usage, HEX);
    while (len) {
      uint8_t cb = (len > 16) ? 16 : len;
      const uint8_t *p = data;
      uint8_t i;
      for (i = 0; i < cb; i++) {
        Serial.printf("%02x ", *p++);
      }
      Serial.print(": ");
      for (i = 0; i < cb; i++) {
        Serial.write(((*data >= ' ') && (*data <= '~')) ? *data : '.');
        data++;
      }
      len -= cb;
      Serial.println();
    }
  }

  return true;
}
```
I have run older test one up to about cnt of 25000 records sent and now with this updated test sketches about 7000 so far.

### CODE REVIEW

**Comment by Defragster** [comment]
Just put updated USB_rawhid.c on my system on a pair of T4's running above posted sketches - off to a good start passing 14,000 messages without fail … will run overnight.

**Comment by KurtE** [comment]
@PaulStoffregen  - Quick update

I did convert the TX to use DMAMEM like the RX and the SEREMU code.

Also just pushed up change to usb.c to get rid of compiler warning when you are building for rawhid. 

It did not include the rawhid.h file.

**Comment by Defragster** [comment]
overnight run here from prior code : 

RawHid Serial: L:9090304 R:294208: Seq:294208  Heap: 20200660

… and counting

**Comment by KurtE** [comment]
@PaulStoffregen  and @Defragster  

I added the fix for SerialUSB1 and SerialUSB2 actual objects were not created on T4.x.  So added the same code that was over on the T3.x side

**Comment by Defragster** [comment]
That fixes the compile issues I saw with Multi Serial!

**Comment by tewarfel** [comment]
For what it's worth, this has fixed a problem I've had with a raw HID application on the Teensy4 as well.  It had been mysteriously hanging after variable run times between 20 minutes to 2 hours.  With the 1.52 beta plus the 4 patches in this pull request, my application has been running without fail for over 12 hours now.  While not a rigorous proof, please consider this as supporting empirical evidence that this set of patches is worth incorporating ASAP.

**Pull request merged**
