### PR TITLE
Added full support for Midi Time Codes and Real Time messages

### PR DESCRIPTION
**Pull request by k-a-r-g**
can now receive and send Midi Time Codes
and send Real Time messages

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
This looks pretty reasonable.  I have just a couple quick questions:

1: Has this been actually tested, both sending and receiving?  (yes, I do get untested pull requests sometimes).  I don't have much MIDI software or gear, so I'm depending on you guys!

2: Is the constant 9 consistent with what's done in F.Best's MIDI library?  Or does that matter?  Back when I originally wrote the USB MIDI stuff, 3.2 was the latest.  I made an effort to use consistent names and constants.  Does that even matter now?

**Comment by k-a-r-g** [comment]
Thank you very much for your interest in my code. I apologise upfront if not everything was clear and/or I implemented something in a rather naive way. It is the very first time that I contribute to a repository that is not my own.

@PaulStoffregen: Yes the code has been tested. On the one hand I use it myself, on the other hand I published it on my blog http://karg-music.blogspot.com several weeks ago, where I got the feedback that it is working well. In this context, the part about receiving Time Codes was written in response to a request of one of my readers who already was using my send functionality.

@Nantonos: Writing an example is actually a good idea, I will look into that.

@PaulStoffregen and Nantonos: Again, my apologies if I have implemented the message type in a more or less naive way. I actually do think, to answer your question Paul, that the code should be as compatible as possible to the existing libraries but in particular to the MIDI standard. So yes, I think it does matter. However, I admittedly did not find much information about the message type numbering scheme, even not about the 0-8 part. What I found was controversial information: from one source I got the message_type = 9 information for the Time Code Quarter Frame messages. In contrast to this, when I instruct Avid Pro Tools to send Time Codes and run them through a Midi Monitor (I used the Hairless MIDI Serial Bridge which is freeware) it identifies it as message_type =2, though. Since 2 is already in use, I decided to trust the other source more and went for type 9. However, I am not home right now and cannot check what the other source was and what is used by F.Best's library. For my arduino projects I have used Best's version 4.2, and I will confirm what it sends as soon as I am home.

**Comment by PaulStoffregen** [comment]
Ok, I'm going to merge this now.  If there's a compelling reason to tweak it later, that can always be done.

**Comment by Nantonos** [comment]
Hello Paul,

Wednesday, July 1, 2015, 1:42:33 PM, you wrote:

> This looks pretty reasonable.  I have just a couple quick questions:
> 1: Has this been actually tested, both sending and receiving? 
> (yes, I do get untested pull requests sometimes).  I don't have much
> MIDI software or gear, so I'm depending on you guys!

> 2: Is the constant 9 consistent with what's done in F.Best's MIDI
> library?

No, it isn't. I'm at work now but from memory, 4.2 library uses one
byte codes (with the channel, if applicable, masked).

>  Or does that matter?  Back when I originally wrote the USB
> MIDI stuff, 3.2 was the latest.  I made an effort to use consistent
> names and constants.  Does that even matter now?

If consistency can be achieved, it is worth striving for.



-- 
Best regards,
 Nantonos                            mailto:nantonos@epona.net

**Comment by capricorn-one** [comment]
Hi @k-a-r-g, 

Did you ever test the functionality of the sendRealTime() function? I had trouble getting it to work with any of my hardware until I made a change to the function. See end of this thread for details:

https://forum.pjrc.com/threads/28969-Audio-adapter-and-library-noob-frustration?p=103131#post103131

Was going to submit a new issue, but I saw this existing thread, I know it's old, but hopefully this is the right place to post about this. After making the change to the function it worked with my hardware.

**Pull request merged**
