### PR TITLE
Fix HardwareSerial TX and RX FIFO size calculation (teensy4)

### LINKED ISSUE #410: TX and RX FIFO size calculation in HardwareSerial.cpp (teensy4) may need correction
https://github.com/PaulStoffregen/cores/blob/041bfbe9ed85b13f1a833b6c81fe2cd54d1b1ac6/teensy4/HardwareSerial.cpp#L155

Strictly speaking, the TX and RX FIFO sizes should look like this:
```c++
uint16_t tx_fifo_size = (1 << (((port->FIFO >> 4) & 0x7) + 1));
if (tx_fifo_size == 2) tx_fifo_size = 1;
uint16_t rx_fifo_size = (1 << (((port->FIFO >> 0) & 0x7) + 1));
if (rx_fifo_size == 2) rx_fifo_size = 1;
```

### PR DESCRIPTION
**Pull request by ssilverman**
Fixes #410.

### CODE REVIEW

**Comment by FrankBoesing** [comment]
(48 Bytes) saved.

Also, please think about moving the whole func to FLASHMEM

**Comment by KurtE** [comment]
I would probably just go with what Frank said... As I don't see anyway to set it and I don't think the hardware is changing any time soon.

**Comment by ssilverman** [comment]
I just updated the commit with fixed sizes for the FIFO (4) and the watermark (2). I kept the fixed calculation commented below and added the reference manual source.

**Comment by ssilverman** [comment]
I think this PR will save some bytes.

**Pull request merged**
