### PR TITLE
Allow to implement endpoint number 1

### PR DESCRIPTION
**Pull request by phdussud**

### CODE REVIEW

**Comment by phdussud** [comment]
Hello, I need to implement a USB device that is a clone of an existing one. I need to implement some endpoint number 1 for an interface. As the code stands, the first supported custom endpoint is 2.

**Comment by PaulStoffregen** [comment]
Endpoint 1 is reserved for a planned future feature

**Comment by phdussud** [comment]
The boiler plate code (reflected by my changes) would still be valid, right?

**Comment by phdussud** [comment]
But the boiler plate code would still be correct, right?

**Comment by PaulStoffregen** [comment]
When Teensy gets this future feature, this code will not work.  I can not merge it.

**Comment by phdussud** [comment]
I see.. 
Thank you very much for your time. 
Patrick.

**Pull request closed without merging**
