### PR TITLE
Resolved: High Temp readings from Temp Monitor

### PR DESCRIPTION
**Pull request by mjs513**
Morning Paul
Based on the discussion on the forum: https://forum.pjrc.com/threads/59813-Teensy-4-0-Internal-Temperature-measurement/page3 and @LAtimes pointing to the final fix: https://forum.pjrc.com/threads/59813-Teensy-4-0-Internal-Temperature-measurement?p=285127&viewfull=1#post285127 I updated tempmon.c to incorporate those changes.  

This resolves the issue I always had with tempmon reading high values for internal temperature that I never could figure out.  Looks like its now fixed.

EDIT:  Now that I woke up fixed another issue with setting Panic Alarm over 95degC. that resulted from change above and maybe there before as well.

### CODE REVIEW

**Comment by mjs513** [comment]
Closing this for now - found another strange bug

**Comment by PaulStoffregen** [comment]
should I merge this one too?

**Comment by mjs513** [comment]
Sorry Paul just saw your comment - not sure why I didn't get a message - but yes please merge it when you get a chance.  It should resolve all the issues with temp readings, as well the issues identified in the thread with temps over 95.  I tested a T4 to about 104 deg without an issue @600Mhz and just running blink - used a hot air gun :)  and not damage to the T4

**Comment by mjs513** [comment]
@PaulStoffregen - if possible could you pick this up for the next beta.

**Comment by PaulStoffregen** [comment]
done

**Comment by mjs513** [comment]
Thank you.  Hope your call goes well

**Pull request merged**
