### PR TITLE
Teensy4: fixed serial buffer head and tail types as in Teensy3.

### PR DESCRIPTION
**Pull request by stawiski**
Discovered with @jacobvartanian .

Same fix as my PR for Teensy3: https://github.com/PaulStoffregen/cores/pull/383

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
Is there really a need for buffers larger than 64K?

**Comment by stawiski** [comment]
@PaulStoffregen Yes. We found the bug while developing a logger device, which needs really large ring buffer. We were declaring over 130KB of RAM for that buffer on Teensy 3.
It all depends on your application, you can surely have a reason to.

**Comment by PaulStoffregen** [comment]
I'm not going to unconditionally change the size.  But I will consider extending the conditional approach used on Teensy 3.x.

**Comment by stawiski** [comment]
I can make a compiler switch for Teensy 4 if you want, it'd check all the sizes of all UART buffers and increase the type to 32 bits if any of the sizes is over 64 KB.

Also, why just not use `uint32_t`? Are you trying to save on RAM?
Teensy 3.6 and 4 are both 32-bit cores, so using a native variable might actually produce less/faster assembly as you don't need to emulate overflows. Can you explain reasoning behind `uint16_t`?

**Pull request closed without merging**
