### PR TITLE
Teensy2 digitalwritefast

### PR DESCRIPTION
**Pull request by KurtE**
For Teensy2...

Add digitalWriteFast, which is a copy of digitalWrite when using built-in const pins else it calls off to digitalWrite.

Add digitalReadFast which simply calls digalRead.

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
This undoes other recent commits.  I'll manually merge it later today....

**Comment by KurtE** [comment]
Sounds good, most be some changes on your side as I believe I am up to sync with what is checked in.

**Comment by KurtE** [comment]
FYI - I think it picked up more semi- changes due to me syncing up to your changes. 
Only 1 changed file (teensy/core_pins.h)

**Comment by PaulStoffregen** [comment]
manually merged.

Thanks!  :)

**Pull request closed without merging**
