### PR TITLE
Teensy 3 & 4 std=c++17 compatibility

### PR DESCRIPTION
**Pull request by AnthonyDiGirolamo**
This change allows compiling the Teensy 3 & 4 cores with the
`arm-none-eabi-g++` `-std=c++17` flag.

These functions are not available when compiling with c++17:

- `isascii()`
- `toascii()`
- `utoa()`
- `itoa()`

Test: Compiled example sketches using Teensyduino 1.53 with these core
changes. No changes were made to boards.txt or platform.txt (which uses
`-std=gnu++14`).

Motivation for this change is to allow building Teensy cores for use
in other frameworks. For our use case it's building [Pigweed](https://cs.opensource.google/pigweed/pigweed) for Teensys. I have it working on Teensy 3.x and 4.x boards with this change:
https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/18001/ but it requires this pull request to compile (since Pigweed needs `-std=c++17`).

We are hoping to run a [Hackaday remoticon workshop](https://hackaday.com/2020/08/04/hackaday-remoticon-our-2020-conference-is-packed-with-workshops-and-were-calling-for-proposals/) and would love it if folks can use Teensy boards for development.

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
Removing INTERNAL, DEFAULT, EXTERNAL will break Arduino API.

**Comment by PaulStoffregen** [comment]
Which parts of this are essential for C++17 use?

**Comment by AnthonyDiGirolamo** [comment]
Thanks for taking a look! Reverted the `INTERNAL, DEFAULT, EXTERNAL` macro changes.

The essential parts seem to be these missing functions:
- `isascii()`
- `toascii()`
- `utoa()`
- `itoa()`

Found a simpler solution by just adding a `nonstd.h` and `utoa()` and `itoa()` functions in `nonstd.c`.

Here are the compiler errors I was getting before the changes:

Missing `isascii and `toascii`:

```
[53/454] c++ arduino_debug/obj/third...o_core_sources.HardwareSerial8.cpp.o
FAILED: arduino_debug/obj/third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/arduino_core_sources.HardwareSerial8.cpp.o
arm-none-eabi-g++ -MMD -MF arduino_debug/obj/third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/arduino_core_sources.HardwareSerial8.cpp.o.d -u_printf_float -O2 -g -Wall -ffunction-sections -fdata-sections -nostdlib -MMD -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10812 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH -IC:/Users/anthony/pigweed/third_party/arduino/cores/teensy\hardware\teensy/avr\cores\teensy4 -fdiagnostics-color -g -fno-common -fno-exceptions -ffunction-sections -fdata-sections -O2 -g -Wall -ffunction-sections -fdata-sections -nostdlib -MMD -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10812 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH -IC:/Users/anthony/pigweed/out/pch -IC:/Users/anthony/pigweed/third_party/arduino/cores/teensy\hardware\teensy/avr\cores\teensy4 -fno-rtti -std=c++17 -Wno-register -include C:/Users/anthony/pigweed/pw_polyfill/language_features.h  -I../pw_polyfill/public_overrides -I../pw_polyfill/standard_library_public -c ../third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/HardwareSerial8.cpp -o arduino_debug/obj/third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/arduino_core_sources.HardwareSerial8.cpp.o
In file included from C:/Users/anthony/pigweed/third_party/arduino/cores/teensy\hardware\teensy/avr\cores\teensy4/WProgram.h:64,
                 from C:/Users/anthony/pigweed/third_party/arduino/cores/teensy\hardware\teensy/avr\cores\teensy4/Arduino.h:6,
                 from ../third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/HardwareSerial8.cpp:31:
C:/Users/anthony/pigweed/third_party/arduino/cores/teensy\hardware\teensy/avr\cores\teensy4/WCharacter.h: In function 'boolean isAscii(int)':
C:/Users/anthony/pigweed/third_party/arduino/cores/teensy\hardware\teensy/avr\cores\teensy4/WCharacter.h:64:12: error: 'isascii' was not declared in this scope; did you mean 'isAscii'?
   64 |   return ( isascii (c) == 0 ? false : true);
      |            ^~~~~~~
      |            isAscii
C:/Users/anthony/pigweed/third_party/arduino/cores/teensy\hardware\teensy/avr\cores\teensy4/WCharacter.h: In function 'int toAscii(int)':
C:/Users/anthony/pigweed/third_party/arduino/cores/teensy\hardware\teensy/avr\cores\teensy4/WCharacter.h:146:10: error: 'toascii' was not declared in this scope; did you mean 'toAscii'?
  146 |   return toascii (c);
      |          ^~~~~~~
      |          toAscii
```

Missing `itoa` and `utoa`:

```
C:\Users\anthony\pigweed>ninja -C out arduino
ninja: Entering directory `out'
[219/389] c++ arduino_debug/obj/thir...4/arduino_core_sources.WString.cpp.o
FAILED: arduino_debug/obj/third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/arduino_core_sources.WString.cpp.o
arm-none-eabi-g++ -MMD -MF arduino_debug/obj/third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/arduino_core_sources.WString.cpp.o.d -u_printf_float -O2 -g -Wall -ffunction-sections -fdata-sections -nostdlib -MMD -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10812 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH -IC:/Users/anthony/pigweed/third_party/arduino/cores/teensy\hardware\teensy/avr\cores\teensy4 -fdiagnostics-color -g -fno-common -fno-exceptions -ffunction-sections -fdata-sections -O2 -g -Wall -ffunction-sections -fdata-sections -nostdlib -MMD -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10812 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH -IC:/Users/anthony/pigweed/out/pch -IC:/Users/anthony/pigweed/third_party/arduino/cores/teensy\hardware\teensy/avr\cores\teensy4 -fno-rtti -std=c++17 -Wno-register -include C:/Users/anthony/pigweed/pw_polyfill/language_features.h  -I../pw_polyfill/public_overrides -I../pw_polyfill/standard_library_public -c ../third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/WString.cpp -o arduino_debug/obj/third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/arduino_core_sources.WString.cpp.o
../third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/WString.cpp: In constructor 'String::String(unsigned char)':
../third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/WString.cpp:70:2: error: 'utoa' was not declared in this scope; did you mean 'ltoa'?
   70 |  utoa(c, buf, 10);
      |  ^~~~
      |  ltoa
../third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/WString.cpp: In constructor 'String::String(int, unsigned char)':
../third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/WString.cpp:78:2: error: 'itoa' was not declared in this scope; did you mean 'ltoa'?
   78 |  itoa(value, buf, base);
      |  ^~~~
      |  ltoa
../third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/WString.cpp: In constructor 'String::String(unsigned int, unsigned char)':
../third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/WString.cpp:86:4: error: 'utoa' was not declared in this scope; did you mean 'ltoa'?
   86 |    utoa(value, buf, base);
      |    ^~~~
      |    ltoa
[224/389] c++ arduino_debug/obj/pw_tokenizer/hash_test.hash_test.cc.o
ninja: build stopped: subcommand failed.
```

**Comment by AnthonyDiGirolamo** [comment]
@PaulStoffregen have you had a chance to look at the revision above? Hoping you might be able to merge before the Hackaday remoticon. Thank you!

**Comment by AnthonyDiGirolamo** [comment]
If interested here are the [Teensy specific docs](https://pigweed.dev/targets/arduino/target_docs.html) and a [sample_project repo](https://pigweed.googlesource.com/pigweed/sample_project/+/refs/heads/master#arduino-example). Both still WIP.

**Comment by PaulStoffregen** [comment]
I manually committed the change to avoid isascii() and toascii().

On the other stuff, looks like we already have them in avr_functions.h, but surrounded by an ifdef that's checking for specific newlib.

https://github.com/PaulStoffregen/cores/blob/master/teensy4/avr_functions.h#L100

Any chance I can talk you into looking at that ifdef and adjusting it as needed?

**Comment by PaulStoffregen** [comment]
Might be simplest to close this PR and do a new one which just changes that ifdef in avr_functions.h.

**Comment by AnthonyDiGirolamo** [comment]
Nice! Modifying that ifdef to check for `__STRICT_ANSI__` in teensy3 and teensy4 did the trick:

```
#if defined(__STRICT_ANSI__) || (defined(_NEWLIB_VERSION) && (__NEWLIB__ < 2 || __NEWLIB__ == 2 && __NEWLIB_MINOR__ < 2))
```

As far as I can tell ([from here](https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html)) that's the only preprocessor check that will tell you if `-std=gnu++*` or `-std=c++*` was used.

```
$ arm-none-eabi-g++ --version
arm-none-eabi-g++ (GNU Arm Embedded Toolchain 9-2020-q2-update) 9.3.1 20200408 (release)
...
$ arm-none-eabi-g++ -std=gnu++17 -x c++  -E -dM -< /dev/null > gnu17.txt
$ arm-none-eabi-g++ -std=c++17 -x c++  -E -dM -< /dev/null > cpp17.txt
$ diff -u gnu17.txt cpp17.txt
--- gnu17.txt   2020-10-26 18:24:44.727337366 -0700
+++ cpp17.txt   2020-10-26 18:24:30.203306223 -0700
@@ -161,6 +161,7 @@
 #define __LACCUM_MAX__ 0X7FFFFFFFFFFFFFFFP-31LK
 #define __FLT32X_HAS_DENORM__ 1
 #define __INT_FAST16_TYPE__ int
+#define __STRICT_ANSI__ 1
 #define __LDBL_HAS_DENORM__ 1
 #define __cplusplus 201703L
 #define __cpp_ref_qualifiers 200710

**Comment by AnthonyDiGirolamo** [comment]
I will open a new pull request for the ifdef above but ran into an issue testing it with teensy4 on master. When linking I get a bunch of errors like:

```
arm-none-eabi/lib/thumb/v7e-m+dp/hard/libstdc++.a(functexcept.o):(.ARM.exidx.text.unlikely._ZSt17__throw_bad_allocv+0x4): relocation truncated to fit: R_ARM_PREL31 against `.ARM.extab.text.unlikely._ZSt17__throw_bad_allocv'
```

The first commit that causes this is error https://github.com/PaulStoffregen/cores/commit/dc567880488dc53ba2e71eb07e04356bda7e2a7e.

I'm still using the arduino recipes in `boards.txt` and `platform.txt` from Teensyduino 1.53. Should any c/cpp/ldflags change? Here's what I'm using:

```
asmflags
  -O2
  -g
  -Wall
  -ffunction-sections
  -fdata-sections
  -nostdlib
  -MMD
  -x
  assembler-with-cpp
  -mthumb
  -mcpu=cortex-m7
  -mfloat-abi=hard
  -mfpu=fpv5-d16
  -D__IMXRT1062__
  -DTEENSYDUINO=153
  -DARDUINO=10812
  -DARDUINO_TEENSY40
  -DF_CPU=600000000
  -DUSB_SERIAL
  -DLAYOUT_US_ENGLISH
  -I/mnt/pigweed/pigweed/third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4

cflags
  -u_printf_float
  -O2
  -g
  -Wall
  -ffunction-sections
  -fdata-sections
  -nostdlib
  -MMD
  -mthumb
  -mcpu=cortex-m7
  -mfloat-abi=hard
  -mfpu=fpv5-d16
  -D__IMXRT1062__
  -DTEENSYDUINO=153
  -DARDUINO=10812
  -DARDUINO_TEENSY40
  -DF_CPU=600000000
  -DUSB_SERIAL
  -DLAYOUT_US_ENGLISH
  -I/mnt/pigweed/pigweed/third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4
  -fdiagnostics-color
  -g
  -fno-common
  -fno-exceptions
  -ffunction-sections
  -fdata-sections

cflags_cc
  -O2
  -g
  -Wall
  -ffunction-sections
  -fdata-sections
  -nostdlib
  -MMD
  -fno-exceptions
  -fpermissive
  -fno-rtti
  -fno-threadsafe-statics
  -felide-constructors
  -Wno-error=narrowing
  -mthumb
  -mcpu=cortex-m7
  -mfloat-abi=hard
  -mfpu=fpv5-d16
  -D__IMXRT1062__
  -DTEENSYDUINO=153
  -DARDUINO=10812
  -DARDUINO_TEENSY40
  -DF_CPU=600000000
  -DUSB_SERIAL
  -DLAYOUT_US_ENGLISH
  -I/mnt/pigweed/pigweed/third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4
  -fno-rtti
  -std=c++17
  -Wno-register
  -include
  /mnt/pigweed/pigweed/pw_polyfill/language_features.h

include_dirs
  //pw_polyfill/public_overrides/
  //pw_polyfill/standard_library_public/
  //pw_tokenizer/public/
  //pw_preprocessor/public/
  //pw_span/public/
  //pw_span/public_overrides/
  //pw_polyfill/public/
  //pw_unit_test/public/
  //pw_unit_test/public_overrides/
  //pw_string/public/
  //pw_status/public/

ldflags
  -u_printf_float
  -O2
  -Wl,--gc-sections,--relax
  -T/mnt/pigweed/pigweed/third_party/arduino/cores/teensy/hardware/teensy/avr/cores/teensy4/imxrt1062.ld
  -mthumb
  -mcpu=cortex-m7
  -mfloat-abi=hard
  -mfpu=fpv5-d16
  -L/mnt/pigweed/pigweed/out
  -L/mnt/pigweed/pigweed/third_party/arduino/cores/teensy/hardware/teensy/../tools//arm/arm-none-eabi/lib
  -fdiagnostics-color
```

**Comment by PaulStoffregen** [comment]
Thanks for the followup.  I've committed this fix.  If there's any remaining problems on this, please reopen the issue.

**Comment by PaulStoffregen** [comment]
We're in early beta testing for 1.54, where "early" means merging lots of fixed long-standard issues (like this one).  Here's the beta from a couple days ago.

https://forum.pjrc.com/threads/64023-Teensyduino-1-54-Beta-2

Please use this to check the compiler flags.  In Arduino, click File > Preferences to turn on verbose output while compiling.

**Pull request closed without merging**
