### PR TITLE
T4-HardwareSerial - RX look at FIFO

### PR DESCRIPTION
**Pull request by KurtE**
Extracted from other PR. #419 

This change only adds the code to look at the RX FIFO when you call available, and read/peak if our software queue is empty, it then checks to see if hardware FIFO has data to extract.

This removes the issue that there is a one character time of no activity before idle is detected and then characters extracted from fifio

I tried it on current beta and 1.8.11 with only this change, with simple sketch that I echo characters from one UART to the next to we tie TX1->RX2, TX2->RX3 ... TX7->RX1..
Sketch:
```
int count_bytes_pending = 0;
elapsedMicros delta_time_echo;
int count_bytes_echoed = 0;
int count_bytes_echoed2 = 0;
int count_bytes_echoed3 = 0;
int count_bytes_echoed4 = 0;
int count_bytes_echoed5 = 0;
int count_bytes_echoed6 = 0;
int count_bytes_echoed7 = 0;

char buffer[128];


void setup() {
  while (!Serial && millis() < 5000) ;
  Serial.begin(115200);
  Serial1.begin(115200);
  Serial2.begin(115200);
  Serial3.begin(115200);
  Serial4.begin(115200);
  Serial5.begin(115200);
  Serial6.begin(115200);
  Serial7.begin(115200);
  delay(500);
  Serial.println("Text entered in Serial monitor will echo to Serial1, to ...");

}

void loop() {
  if (Serial.available()) {
    uint16_t cb = Serial.available();
    uint16_t cbAvailWrite = Serial1.availableForWrite();
    if (cb > cbAvailWrite) cb = cbAvailWrite;
    Serial.readBytes(buffer, cb);
    Serial1.write(buffer, cb);
    count_bytes_pending += cb;
    delta_time_echo = 0;
  }
  if (count_bytes_pending && (delta_time_echo > 1000000)) {
    // something went wrong?
    Serial.printf("Timeout: %u %u %u %u %u %u %u\n", count_bytes_echoed, count_bytes_echoed2, count_bytes_echoed3,
                  count_bytes_echoed4, count_bytes_echoed5, count_bytes_echoed6, count_bytes_echoed7);
    delta_time_echo = 0;
    count_bytes_pending = 0;
  }
}

void serialEvent1() {
  uint16_t cb = Serial1.available();
  uint16_t cbAvailWrite = Serial.availableForWrite();
  if (cb > cbAvailWrite) cb = cbAvailWrite;
  Serial1.readBytes(buffer, cb);
  Serial.write(buffer, cb);
  count_bytes_pending -= cb;
  count_bytes_echoed += cb;

  if (count_bytes_pending <= 0) {
    uint32_t delta_time = delta_time_echo;
    Serial.printf(" ##(%d)cb: %u delta time: %u\n", count_bytes_pending,
                  count_bytes_echoed, delta_time);
    count_bytes_echoed = 0;
    delta_time_echo = 0;
  }
}

inline void processSerialEvent(HardwareSerial &hserial, int &cbEchoed) {
  uint16_t cb = hserial.available();
  uint16_t cbAvailWrite = hserial.availableForWrite();
  if (cb > cbAvailWrite) cb = cbAvailWrite;
  hserial.readBytes(buffer, cb);
  hserial.write(buffer, cb);
  cbEchoed += cb;
}

void serialEvent2() {
  processSerialEvent(Serial2, count_bytes_echoed2);
}
void serialEvent3() {
  processSerialEvent(Serial3, count_bytes_echoed3);
}
void serialEvent4() {
  processSerialEvent(Serial4, count_bytes_echoed4);
}
void serialEvent5() {
  processSerialEvent(Serial5, count_bytes_echoed5);
}
void serialEvent6() {
  processSerialEvent(Serial6, count_bytes_echoed6);
}
void serialEvent7() {
  processSerialEvent(Serial7, count_bytes_echoed7);
}
```
Before updates a couple of timings: 
```
abcdefghijklmnopqrstuvwxyz

 ##(0)cb: 28 delta time: 4085
012345678

 ##(0)cb: 11 delta time: 2619
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

 ##(0)cb: 119 delta time: 7472
```

With these changes:
```
abcdefghijklmnopqrstuvwxyz

 ##(0)cb: 28 delta time: 2973
012345678

 ##(0)cb: 11 delta time: 1499
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

 ##(0)cb: 119 delta time: 6352
```

Again not a show stopper, but... 

EDIT: updated sketch to use buffer and check for availForWrite for correctness.  Did not really change times...

### CODE REVIEW

**Comment by KurtE** [comment]
@PaulStoffregen - At some point it would be good if you could take a look at this and see what you think.

The issue is that with T4 hardware serial - there is often a one character time length delay before you might receive a character.  I have seen this with some of my own code where trying to driver servos, and I do a request to receive data to the servo, convert the serial port to receive mode (half duplex) and wait until I receive the packet of data.  And sometimes my code would time out as I may not expect that long of a delay before typically the last character is received. 

As I mentioned earlier, there is a different PR #419 that I believe removed this delay, but that could cause more interrupts...

**Comment by PaulStoffregen** [comment]
Quick followup - I want to merge this when we start 1.53... probably in a couple weeks after the dust settings from Teensy 4.1 and Teensyduino 1.52.

**Comment by KurtE** [comment]
Sounds like a plan.  I don't see doing it during this release cycle, due to you probably being a bit busy with a few other things ;D

**Comment by KurtE** [comment]
Hi @PaulStoffregen  - Wonder if this is about the right time?  Not sure when you are planning a beta for the next version, but would be great to do before Arduino suddenly releases a new release and you have to do a quick new version. 

Hope things are going well!

**Pull request merged**
