### PR TITLE
Update imxrt.h for encoder structure

### PR DESCRIPTION
**Pull request by mjs513**
Hi Paul
Created a Quad Encoder library for the Teensy 4 but to make life simpler I updated the encoder registers to create encoder structure.  Right now basic functions quad encoder function working but probably still needs some testing.

Thanks
Mike

### CODE REVIEW

**Comment by mjs513** [comment]
Just for reference the finished lib with some examples is on my GitHub: https://github.com/mjs513/Teensy-4.x-Quad-Encoder-Library

**Comment by mjs513** [comment]
Paul
Per your direction on deleting reg names, "But do not delete the already defined full register names. Convert them to the new struct.", i went back in and added the register names using the typedef structure for IMXRT_ENC_t.  Hopefully, I did it right :).  But seriously if I knew I wouldn't have deleted them. Sorry.

**Comment by PaulStoffregen** [comment]
Thanks for updating this.  I really should have commented earlier... but been so far behind since T4 release.  Finally getting caught up now and back to software work.

**Comment by mjs513** [comment]
Not a problem Paul.  Know you have been crazy busy running a business and trying to do development work.  Good to see you back to the doing the fun stuff :)

**Pull request merged**
