### PR TITLE
Teensy3 usb triple serial

### PR DESCRIPTION
**Pull request by geertu**
Add support for dual (USB_DUAL_SERIAL) and triple (USB_TRIPLE_SERIAL) serial port configurations, providing a composite USB device, comprised of two or three serial ports.
The second serial port is called usb_serial2 (C) or SerialA (C++).
The third serial port is called usb_serial3 (C) or SerialB (C++).

### CODE REVIEW

**Comment by luni64** [comment]
Wow, that might be extremely useful for debugging if you need Serial for normal communication to the PC. 

I gave it a quick try, it compiles without issues and generates the second port (WIN10) which appears in the device manager.
Both ports can be opened with putty, and the normal Serial works as usual.
But, I can't use SerialB or usb_serial2. It seems to be not defined. Do I need to change other defines besides changing -DUSB_SERIAL to -DUSB_DUAL_SERIAL to make this work?

**Comment by geertu** [comment]
Changing -DUSB_SERIAL to -DUSB_DUAL_SERIAL should be sufficient.
After that, any of the following should work:
        usb_serial2_putchar('x');
        SerialA.write("hello\n\r");

TBH, I'm not using the Arduino environment, but C and Makefiles, so I may be missing a minor detail.
For reference, my full project on top of this is at https://github.com/geertu/teensy3-bcu2

**Comment by luni64** [comment]
> TBH, I'm not using the Arduino environment, but C and Makefiles, so I may be missing a minor detail. 

So do I...   Found it, was my fault I changed the define in the makefile but forgot to do the same change in the intellisense config. So, vsCode marked SerialA as not defined and I believed it. Silly me...

Everything runs out of the box, the only issue I see at the moment is the compatibility to the uploaders. Tried TyCommander which gets confused. I'll give teensy.exe a go later.

**Comment by luni64** [comment]
Same with Teensy.exe, after resetting, it looses the board. Pressing the programming button works of course.

**Comment by PaulStoffregen** [comment]
I really do appreciate that you've contributed this code back to the core library.  But much the macro trickery appears to be incompatible with the Arduino IDE.  I need to undo some of that work.  Just wanted to let you know... it's not that I don't appreciate everything you've done here.  This needs to work with the Arduino IDE (appears that was never tested).  Just wanted to let you know why I have to undo parts of this.

**Comment by geertu** [comment]
> I really do appreciate that you've contributed this code back to the core library. But much the macro trickery appears to be incompatible with the Arduino IDE. I need to undo some of that work. Just wanted to let you know... it's not that I don't appreciate everything you've done here. This needs to work with the Arduino IDE (appears that was never tested). Just wanted to let you know why I have to undo parts of this.

Np.  What exactly is failing?
BTW, I'm a bit confused: according to GitHub, my pull request was successfully merged and closed, and I don't see any reverts?
Thanks!

**Comment by PaulStoffregen** [comment]
I've just pushed the reverts.  This broke things very badly for building with the Arduino IDE.

I'm going through it now to manually part parts back in.  But this sort of tricky preprocessor usage, while elegant, it utterly incompatible with the Arduino IDE.  We just can't use it like this.

**Comment by geertu** [comment]
> I've just pushed the reverts. This broke things very badly for building with the Arduino IDE.
> 
> I'm going through it now to manually part parts back in. But this sort of tricky preprocessor usage, while elegant, it utterly incompatible with the Arduino IDE. We just can't use it like this.

Thanks, I'll hope to have a closer look at the issues tomorrow.

**Comment by PaulStoffregen** [comment]
I'm working now to convert it to a large, not-nearly-so-pretty expansion of the macros, so it can build with Arduino.  Should have it in a few hours...

**Comment by PaulStoffregen** [comment]
It's not pretty and it duplicates (triplicates) a lot of code, but compiles with Arduino IDE.
https://github.com/PaulStoffregen/cores/commit/cd4c30fde5d09d0bc19f7f832b7cffff474932a5

**Comment by luni64** [comment]
Great, do you plan to make Teensy.exe compatible to this?

**Comment by PaulStoffregen** [comment]
Yes, but I may release a first 1.52 beta before updating the tools to properly deal with these 2 new USB types.

**Comment by PaulStoffregen** [comment]
Fixing the code so there aren't compile errors was of course the most urgent thing.  Can't start a beta with code that's not compiling in Arduino.

**Comment by luni64** [comment]
Sure,  just tested the new version with Win10 and Arduino 1.8.5 to build. Works perfectly.

**Comment by geertu** [comment]
> It's not pretty and it duplicates (triplicates) a lot of code, but compiles with Arduino IDE.
> [cd4c30f](https://github.com/PaulStoffregen/cores/commit/cd4c30fde5d09d0bc19f7f832b7cffff474932a5)

Thanks, that looks pretty similar to what I had before introducing serial_port and the macros for deduplication.
I went over all changes, and it looks good to me.  Except for a harmless port2/3 mixup (pull request sent ;-)

BTW, I can confirm commit 7f3222c98504394b ("Allow any of the Daul & Triple serial to request reboot") fixes automatic reboot for programming for me. Thanks!

**Comment by geertu** [comment]
Hi Paul,

> > I've just pushed the reverts. This broke things very badly for building with the Arduino IDE.
> > I'm going through it now to manually part parts back in. But this sort of tricky preprocessor usage, while elegant, it utterly incompatible with the Arduino IDE. We just can't use it like this.
> 
> Thanks, I'll hope to have a closer look at the issues tomorrow.
> My apologies, I should have verified with the Arduino IDE before.

So I gave it a try in the Arduino IDE (replaced cores in installed teensyduino by this repo, and added dual/triple serial defs to teensy/avr/boards.txt).

It turns out the sole offender in my macros is
    #define USB_SERIAL_SUFFIX      /* none */
    #define SERIAL_CLASS_SUFFIX    /* none */
in teensy3/usb_serial.h.  Changing to C++-style comments doesn't help.
Due to the use of the "-CC" option, the compiler doesn't discard comments, and converts all C++-style comments inside a macro to C-style comments :-( As plain Arduino also uses "-CC", removing this is not an option, I guess.  Do you know the rationale behind using this option?
Replacing the offending lines by
    #define USB_SERIAL_SUFFIX
    #define SERIAL_CLASS_SUFFIX
makes it build for me.

However, I'm not 100% confident this fixes all issues.  USB serial operation and programming from the Arduino IDE (arduino-1.8.10+teensyduino-1.48) seems to be very unreliable and unpredictable for me.  Note that that is even the case when using a cores version from before you merged my branch, so these issues may be completely unrelated.

Thanks!

**Comment by PaulStoffregen** [comment]
I ported this to Teensy 4.0.

I'm going to make one more change before releasing a beta test.  Arduino's naming convention seems to be SerialUSB.  We already support SerialUSB as an alias for Serial (and I believe Arduino does too on their board where they are the same_.  So I'm going to go with SerialUSB1 and SerialUSB2 rather than SerialA and SerialB.  Hopefully that's not too painful at this point.

**Comment by WestfW** [comment]
Make SerialUSB0 an alias for the original SerialUSB, too?

**Comment by geertu** [comment]
> I ported this to Teensy 4.0.

Nice!
 
> I'm going to make one more change before releasing a beta test. Arduino's naming convention seems to be SerialUSB. We already support SerialUSB as an alias for Serial (and I believe Arduino does too on their board where they are the same). So I'm going to go with SerialUSB1 and SerialUSB2 rather than SerialA and SerialB. Hopefully that's not too painful at this point.

That makes perfect sense.   I wasn't aware of SerialUSB, so that's why I went with A and B, to avoid interfering with the hardware serial numbering.

BTW, shouldn't usb_serial2* and usb_serial3* be renamed to usb_serial1* and usb_serial2*, too, to preserve consistency. Right now we have:
teensy3/usb_serial.h:extern usb_serial_class Serial;
teensy3/usb_serial2.h:extern usb_serial2_class SerialUSB1;
teensy3/usb_serial3.h:extern usb_serial3_class SerialUSB2;
teensy4/usb_serial.h:extern usb_serial_class Serial;
teensy4/usb_serial.h:extern usb_serial2_class SerialUSB1;
teensy4/usb_serial.h:extern usb_serial3_class SerialUSB2;

**Comment by PaulStoffregen** [comment]
I'm ok with the internal names not being consistent with the Arduino API names.  At this point, I'm pretty happy with "ain't broke, don't fix".

@WestfW - Does Arduino use SerialUSB0, or Serial0, or "0" on the end of any of the port names for their boards?  I do want the public API names to be consistent with the conventions Arduino is using.

**Comment by mjs513** [comment]
Kind of curious now that someone pointed this discussion out to me - but what changes are necessary to boards.txt to get it to work if I wanted to give it a test?  Or is it too early to ask.

**Comment by geertu** [comment]
> Kind of curious now that someone pointed this discussion out to me - but what changes are necessary to boards.txt to get it to work if I wanted to give it a test? Or is it too early to ask.
> 
> UPDATE: Forget I asked - figured it out dummy that I am. It works with T4 by the way.

JFTR, for Teensy 3.1/3.2, add to hardware/teensy/avr/boards.txt:

    teensy31.menu.usb.dualserial=Dual serial
    teensy31.menu.usb.dualserial.build.usbtype=USB_DUAL_SERIAL
    teensy31.menu.usb.tripleserial=Triple serial
    teensy31.menu.usb.tripleserial.build.usbtype=USB_TRIPLE_SERIAL

**Comment by mjs513** [comment]
Yep - that's pretty much what I had done, except used Serial2 - Serial3 after usb.
Thanks.

**Pull request merged**
