### PR TITLE
Update some availableForWrite() declarations to be virtual

### PR DESCRIPTION
**Pull request by ssilverman**
These are overriding functions.

Note: Because this changes some core stuff, don't trust just me that it works. This should probably have at least one or two other people run tests.

### CODE REVIEW

**Comment by ssilverman** [comment]
By not declaring these as "overriding", if any objects are cast to a `Print`, then the wrong `availableForWrite()` function would get called.

**Comment by ssilverman** [comment]
But this might be good to have, at least, for consistency.

**Comment by ssilverman** [comment]
Spec details:

> Then this function in the class Derived is also virtual (whether or not the keyword virtual is used in its declaration) and overrides Base::vf (whether or not the word override is used in its declaration).

Source: https://en.cppreference.com/w/cpp/language/virtual

**Comment by PaulStoffregen** [comment]
Looks like Arduino is now using virtual for availableForWrite(), so seem pretty safe to give this a try.

**Pull request merged**
