### PR TITLE
allow setting buffersizes

### PR DESCRIPTION
**Pull request by FrankBoesing**
If this is ok, i can provide this for the other uarts, too.
+ It is possible to deactivate them completely via #define
(saves memory esp. on LC)

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
Let's make this SERIAL1_TX_BUFFER_SIZE and SERIAL1_RX_BUFFER_SIZE.

**Comment by PaulStoffregen** [comment]
Also considering a proposal (not yet public) for an extension to add a 2nd buffer at runtime.  That will add overhead, so still undecided if I like the idea....

**Comment by FrankBoesing** [comment]
No problem - want it for all serials ? With disable ?
Hm.. a second buffer would be a bit slower. But having that at runtime, would be more easy to use..

**Comment by PaulStoffregen** [comment]
Sure, let's do it for all 6.  Can you amend this PR?

**Comment by FrankBoesing** [comment]
Don't know how .)  Easier for me is to close it :) I make a new one.

**Pull request closed without merging**
